version: "3.9"

services:
  api:
    build:
      context: .
      target: prod
    ports:
      - "9000"
    restart: "always"
    volumes:
      - .:/app
      - ./mnt/public:/app/public
    env_file:
      - ./.env
    networks:
      - "api.network"
    #    # Starts up 5 replicas of the same image
    #    deploy:
    #      replicas: 5
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asinyoDB@123
    volumes:
      - ./cmd/scripts:/docker-entrypoint-initdb.d/:rw
      - ./mnt/mysql:/var/lib/mysql
    expose:
      - 3306
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --interactive_timeout=1048576, --max_connections=1024, --log-warnings=1]
    networks:
      - "api.network"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "80"
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - /sessions
      - ~/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - db
    networks:
      - "api.network"
  nginx:
    image: nginx:latest
    volumes:
      - ./cmd/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - "api.network"
networks:
  api.network:
volumes:
  mysql:
  public:
