// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SeyramWood/ent/agent"
	"github.com/SeyramWood/ent/customer"
	"github.com/SeyramWood/ent/favourite"
	"github.com/SeyramWood/ent/merchant"
	"github.com/SeyramWood/ent/predicate"
	"github.com/SeyramWood/ent/product"
)

// FavouriteQuery is the builder for querying Favourite entities.
type FavouriteQuery struct {
	config
	limit        *int
	offset       *int
	unique       *bool
	order        []OrderFunc
	fields       []string
	predicates   []predicate.Favourite
	withMerchant *MerchantQuery
	withAgent    *AgentQuery
	withCustomer *CustomerQuery
	withProduct  *ProductQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FavouriteQuery builder.
func (fq *FavouriteQuery) Where(ps ...predicate.Favourite) *FavouriteQuery {
	fq.predicates = append(fq.predicates, ps...)
	return fq
}

// Limit adds a limit step to the query.
func (fq *FavouriteQuery) Limit(limit int) *FavouriteQuery {
	fq.limit = &limit
	return fq
}

// Offset adds an offset step to the query.
func (fq *FavouriteQuery) Offset(offset int) *FavouriteQuery {
	fq.offset = &offset
	return fq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fq *FavouriteQuery) Unique(unique bool) *FavouriteQuery {
	fq.unique = &unique
	return fq
}

// Order adds an order step to the query.
func (fq *FavouriteQuery) Order(o ...OrderFunc) *FavouriteQuery {
	fq.order = append(fq.order, o...)
	return fq
}

// QueryMerchant chains the current query on the "merchant" edge.
func (fq *FavouriteQuery) QueryMerchant() *MerchantQuery {
	query := &MerchantQuery{config: fq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(favourite.Table, favourite.FieldID, selector),
			sqlgraph.To(merchant.Table, merchant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, favourite.MerchantTable, favourite.MerchantColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgent chains the current query on the "agent" edge.
func (fq *FavouriteQuery) QueryAgent() *AgentQuery {
	query := &AgentQuery{config: fq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(favourite.Table, favourite.FieldID, selector),
			sqlgraph.To(agent.Table, agent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, favourite.AgentTable, favourite.AgentColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCustomer chains the current query on the "customer" edge.
func (fq *FavouriteQuery) QueryCustomer() *CustomerQuery {
	query := &CustomerQuery{config: fq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(favourite.Table, favourite.FieldID, selector),
			sqlgraph.To(customer.Table, customer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, favourite.CustomerTable, favourite.CustomerColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProduct chains the current query on the "product" edge.
func (fq *FavouriteQuery) QueryProduct() *ProductQuery {
	query := &ProductQuery{config: fq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(favourite.Table, favourite.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, favourite.ProductTable, favourite.ProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Favourite entity from the query.
// Returns a *NotFoundError when no Favourite was found.
func (fq *FavouriteQuery) First(ctx context.Context) (*Favourite, error) {
	nodes, err := fq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{favourite.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fq *FavouriteQuery) FirstX(ctx context.Context) *Favourite {
	node, err := fq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Favourite ID from the query.
// Returns a *NotFoundError when no Favourite ID was found.
func (fq *FavouriteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{favourite.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fq *FavouriteQuery) FirstIDX(ctx context.Context) int {
	id, err := fq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Favourite entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Favourite entity is found.
// Returns a *NotFoundError when no Favourite entities are found.
func (fq *FavouriteQuery) Only(ctx context.Context) (*Favourite, error) {
	nodes, err := fq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{favourite.Label}
	default:
		return nil, &NotSingularError{favourite.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fq *FavouriteQuery) OnlyX(ctx context.Context) *Favourite {
	node, err := fq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Favourite ID in the query.
// Returns a *NotSingularError when more than one Favourite ID is found.
// Returns a *NotFoundError when no entities are found.
func (fq *FavouriteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{favourite.Label}
	default:
		err = &NotSingularError{favourite.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fq *FavouriteQuery) OnlyIDX(ctx context.Context) int {
	id, err := fq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Favourites.
func (fq *FavouriteQuery) All(ctx context.Context) ([]*Favourite, error) {
	if err := fq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return fq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (fq *FavouriteQuery) AllX(ctx context.Context) []*Favourite {
	nodes, err := fq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Favourite IDs.
func (fq *FavouriteQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := fq.Select(favourite.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fq *FavouriteQuery) IDsX(ctx context.Context) []int {
	ids, err := fq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fq *FavouriteQuery) Count(ctx context.Context) (int, error) {
	if err := fq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return fq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (fq *FavouriteQuery) CountX(ctx context.Context) int {
	count, err := fq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fq *FavouriteQuery) Exist(ctx context.Context) (bool, error) {
	if err := fq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return fq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (fq *FavouriteQuery) ExistX(ctx context.Context) bool {
	exist, err := fq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FavouriteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fq *FavouriteQuery) Clone() *FavouriteQuery {
	if fq == nil {
		return nil
	}
	return &FavouriteQuery{
		config:       fq.config,
		limit:        fq.limit,
		offset:       fq.offset,
		order:        append([]OrderFunc{}, fq.order...),
		predicates:   append([]predicate.Favourite{}, fq.predicates...),
		withMerchant: fq.withMerchant.Clone(),
		withAgent:    fq.withAgent.Clone(),
		withCustomer: fq.withCustomer.Clone(),
		withProduct:  fq.withProduct.Clone(),
		// clone intermediate query.
		sql:    fq.sql.Clone(),
		path:   fq.path,
		unique: fq.unique,
	}
}

// WithMerchant tells the query-builder to eager-load the nodes that are connected to
// the "merchant" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FavouriteQuery) WithMerchant(opts ...func(*MerchantQuery)) *FavouriteQuery {
	query := &MerchantQuery{config: fq.config}
	for _, opt := range opts {
		opt(query)
	}
	fq.withMerchant = query
	return fq
}

// WithAgent tells the query-builder to eager-load the nodes that are connected to
// the "agent" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FavouriteQuery) WithAgent(opts ...func(*AgentQuery)) *FavouriteQuery {
	query := &AgentQuery{config: fq.config}
	for _, opt := range opts {
		opt(query)
	}
	fq.withAgent = query
	return fq
}

// WithCustomer tells the query-builder to eager-load the nodes that are connected to
// the "customer" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FavouriteQuery) WithCustomer(opts ...func(*CustomerQuery)) *FavouriteQuery {
	query := &CustomerQuery{config: fq.config}
	for _, opt := range opts {
		opt(query)
	}
	fq.withCustomer = query
	return fq
}

// WithProduct tells the query-builder to eager-load the nodes that are connected to
// the "product" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FavouriteQuery) WithProduct(opts ...func(*ProductQuery)) *FavouriteQuery {
	query := &ProductQuery{config: fq.config}
	for _, opt := range opts {
		opt(query)
	}
	fq.withProduct = query
	return fq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Favourite.Query().
//		GroupBy(favourite.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (fq *FavouriteQuery) GroupBy(field string, fields ...string) *FavouriteGroupBy {
	grbuild := &FavouriteGroupBy{config: fq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return fq.sqlQuery(ctx), nil
	}
	grbuild.label = favourite.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Favourite.Query().
//		Select(favourite.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (fq *FavouriteQuery) Select(fields ...string) *FavouriteSelect {
	fq.fields = append(fq.fields, fields...)
	selbuild := &FavouriteSelect{FavouriteQuery: fq}
	selbuild.label = favourite.Label
	selbuild.flds, selbuild.scan = &fq.fields, selbuild.Scan
	return selbuild
}

func (fq *FavouriteQuery) prepareQuery(ctx context.Context) error {
	for _, f := range fq.fields {
		if !favourite.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fq.path != nil {
		prev, err := fq.path(ctx)
		if err != nil {
			return err
		}
		fq.sql = prev
	}
	return nil
}

func (fq *FavouriteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Favourite, error) {
	var (
		nodes       = []*Favourite{}
		withFKs     = fq.withFKs
		_spec       = fq.querySpec()
		loadedTypes = [4]bool{
			fq.withMerchant != nil,
			fq.withAgent != nil,
			fq.withCustomer != nil,
			fq.withProduct != nil,
		}
	)
	if fq.withMerchant != nil || fq.withAgent != nil || fq.withCustomer != nil || fq.withProduct != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, favourite.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Favourite).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Favourite{config: fq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fq.withMerchant; query != nil {
		if err := fq.loadMerchant(ctx, query, nodes, nil,
			func(n *Favourite, e *Merchant) { n.Edges.Merchant = e }); err != nil {
			return nil, err
		}
	}
	if query := fq.withAgent; query != nil {
		if err := fq.loadAgent(ctx, query, nodes, nil,
			func(n *Favourite, e *Agent) { n.Edges.Agent = e }); err != nil {
			return nil, err
		}
	}
	if query := fq.withCustomer; query != nil {
		if err := fq.loadCustomer(ctx, query, nodes, nil,
			func(n *Favourite, e *Customer) { n.Edges.Customer = e }); err != nil {
			return nil, err
		}
	}
	if query := fq.withProduct; query != nil {
		if err := fq.loadProduct(ctx, query, nodes, nil,
			func(n *Favourite, e *Product) { n.Edges.Product = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fq *FavouriteQuery) loadMerchant(ctx context.Context, query *MerchantQuery, nodes []*Favourite, init func(*Favourite), assign func(*Favourite, *Merchant)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Favourite)
	for i := range nodes {
		if nodes[i].merchant_favourites == nil {
			continue
		}
		fk := *nodes[i].merchant_favourites
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(merchant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "merchant_favourites" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (fq *FavouriteQuery) loadAgent(ctx context.Context, query *AgentQuery, nodes []*Favourite, init func(*Favourite), assign func(*Favourite, *Agent)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Favourite)
	for i := range nodes {
		if nodes[i].agent_favourites == nil {
			continue
		}
		fk := *nodes[i].agent_favourites
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(agent.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "agent_favourites" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (fq *FavouriteQuery) loadCustomer(ctx context.Context, query *CustomerQuery, nodes []*Favourite, init func(*Favourite), assign func(*Favourite, *Customer)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Favourite)
	for i := range nodes {
		if nodes[i].customer_favourites == nil {
			continue
		}
		fk := *nodes[i].customer_favourites
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(customer.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "customer_favourites" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (fq *FavouriteQuery) loadProduct(ctx context.Context, query *ProductQuery, nodes []*Favourite, init func(*Favourite), assign func(*Favourite, *Product)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Favourite)
	for i := range nodes {
		if nodes[i].product_favourites == nil {
			continue
		}
		fk := *nodes[i].product_favourites
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(product.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "product_favourites" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (fq *FavouriteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fq.querySpec()
	_spec.Node.Columns = fq.fields
	if len(fq.fields) > 0 {
		_spec.Unique = fq.unique != nil && *fq.unique
	}
	return sqlgraph.CountNodes(ctx, fq.driver, _spec)
}

func (fq *FavouriteQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := fq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (fq *FavouriteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   favourite.Table,
			Columns: favourite.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: favourite.FieldID,
			},
		},
		From:   fq.sql,
		Unique: true,
	}
	if unique := fq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := fq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, favourite.FieldID)
		for i := range fields {
			if fields[i] != favourite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fq *FavouriteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fq.driver.Dialect())
	t1 := builder.Table(favourite.Table)
	columns := fq.fields
	if len(columns) == 0 {
		columns = favourite.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fq.sql != nil {
		selector = fq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fq.unique != nil && *fq.unique {
		selector.Distinct()
	}
	for _, p := range fq.predicates {
		p(selector)
	}
	for _, p := range fq.order {
		p(selector)
	}
	if offset := fq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FavouriteGroupBy is the group-by builder for Favourite entities.
type FavouriteGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fgb *FavouriteGroupBy) Aggregate(fns ...AggregateFunc) *FavouriteGroupBy {
	fgb.fns = append(fgb.fns, fns...)
	return fgb
}

// Scan applies the group-by query and scans the result into the given value.
func (fgb *FavouriteGroupBy) Scan(ctx context.Context, v any) error {
	query, err := fgb.path(ctx)
	if err != nil {
		return err
	}
	fgb.sql = query
	return fgb.sqlScan(ctx, v)
}

func (fgb *FavouriteGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range fgb.fields {
		if !favourite.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := fgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (fgb *FavouriteGroupBy) sqlQuery() *sql.Selector {
	selector := fgb.sql.Select()
	aggregation := make([]string, 0, len(fgb.fns))
	for _, fn := range fgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(fgb.fields)+len(fgb.fns))
		for _, f := range fgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(fgb.fields...)...)
}

// FavouriteSelect is the builder for selecting fields of Favourite entities.
type FavouriteSelect struct {
	*FavouriteQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (fs *FavouriteSelect) Scan(ctx context.Context, v any) error {
	if err := fs.prepareQuery(ctx); err != nil {
		return err
	}
	fs.sql = fs.FavouriteQuery.sqlQuery(ctx)
	return fs.sqlScan(ctx, v)
}

func (fs *FavouriteSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := fs.sql.Query()
	if err := fs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
