// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SeyramWood/ent/merchantstore"
	"github.com/SeyramWood/ent/predicate"
)

// MerchantStoreDelete is the builder for deleting a MerchantStore entity.
type MerchantStoreDelete struct {
	config
	hooks    []Hook
	mutation *MerchantStoreMutation
}

// Where appends a list predicates to the MerchantStoreDelete builder.
func (msd *MerchantStoreDelete) Where(ps ...predicate.MerchantStore) *MerchantStoreDelete {
	msd.mutation.Where(ps...)
	return msd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (msd *MerchantStoreDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, msd.sqlExec, msd.mutation, msd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (msd *MerchantStoreDelete) ExecX(ctx context.Context) int {
	n, err := msd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (msd *MerchantStoreDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(merchantstore.Table, sqlgraph.NewFieldSpec(merchantstore.FieldID, field.TypeInt))
	if ps := msd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, msd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	msd.mutation.done = true
	return affected, err
}

// MerchantStoreDeleteOne is the builder for deleting a single MerchantStore entity.
type MerchantStoreDeleteOne struct {
	msd *MerchantStoreDelete
}

// Where appends a list predicates to the MerchantStoreDelete builder.
func (msdo *MerchantStoreDeleteOne) Where(ps ...predicate.MerchantStore) *MerchantStoreDeleteOne {
	msdo.msd.mutation.Where(ps...)
	return msdo
}

// Exec executes the deletion query.
func (msdo *MerchantStoreDeleteOne) Exec(ctx context.Context) error {
	n, err := msdo.msd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{merchantstore.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (msdo *MerchantStoreDeleteOne) ExecX(ctx context.Context) {
	if err := msdo.Exec(ctx); err != nil {
		panic(err)
	}
}
