// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SeyramWood/ent/product"
	"github.com/SeyramWood/ent/productcategorymajor"
	"github.com/SeyramWood/ent/productcategoryminor"
)

// ProductCategoryMajorCreate is the builder for creating a ProductCategoryMajor entity.
type ProductCategoryMajorCreate struct {
	config
	mutation *ProductCategoryMajorMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (pcmc *ProductCategoryMajorCreate) SetCreatedAt(t time.Time) *ProductCategoryMajorCreate {
	pcmc.mutation.SetCreatedAt(t)
	return pcmc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pcmc *ProductCategoryMajorCreate) SetNillableCreatedAt(t *time.Time) *ProductCategoryMajorCreate {
	if t != nil {
		pcmc.SetCreatedAt(*t)
	}
	return pcmc
}

// SetUpdatedAt sets the "updated_at" field.
func (pcmc *ProductCategoryMajorCreate) SetUpdatedAt(t time.Time) *ProductCategoryMajorCreate {
	pcmc.mutation.SetUpdatedAt(t)
	return pcmc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pcmc *ProductCategoryMajorCreate) SetNillableUpdatedAt(t *time.Time) *ProductCategoryMajorCreate {
	if t != nil {
		pcmc.SetUpdatedAt(*t)
	}
	return pcmc
}

// SetCategory sets the "category" field.
func (pcmc *ProductCategoryMajorCreate) SetCategory(s string) *ProductCategoryMajorCreate {
	pcmc.mutation.SetCategory(s)
	return pcmc
}

// AddMinorIDs adds the "minors" edge to the ProductCategoryMinor entity by IDs.
func (pcmc *ProductCategoryMajorCreate) AddMinorIDs(ids ...int) *ProductCategoryMajorCreate {
	pcmc.mutation.AddMinorIDs(ids...)
	return pcmc
}

// AddMinors adds the "minors" edges to the ProductCategoryMinor entity.
func (pcmc *ProductCategoryMajorCreate) AddMinors(p ...*ProductCategoryMinor) *ProductCategoryMajorCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcmc.AddMinorIDs(ids...)
}

// AddProductIDs adds the "products" edge to the Product entity by IDs.
func (pcmc *ProductCategoryMajorCreate) AddProductIDs(ids ...int) *ProductCategoryMajorCreate {
	pcmc.mutation.AddProductIDs(ids...)
	return pcmc
}

// AddProducts adds the "products" edges to the Product entity.
func (pcmc *ProductCategoryMajorCreate) AddProducts(p ...*Product) *ProductCategoryMajorCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcmc.AddProductIDs(ids...)
}

// Mutation returns the ProductCategoryMajorMutation object of the builder.
func (pcmc *ProductCategoryMajorCreate) Mutation() *ProductCategoryMajorMutation {
	return pcmc.mutation
}

// Save creates the ProductCategoryMajor in the database.
func (pcmc *ProductCategoryMajorCreate) Save(ctx context.Context) (*ProductCategoryMajor, error) {
	var (
		err  error
		node *ProductCategoryMajor
	)
	pcmc.defaults()
	if len(pcmc.hooks) == 0 {
		if err = pcmc.check(); err != nil {
			return nil, err
		}
		node, err = pcmc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductCategoryMajorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pcmc.check(); err != nil {
				return nil, err
			}
			pcmc.mutation = mutation
			if node, err = pcmc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pcmc.hooks) - 1; i >= 0; i-- {
			if pcmc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pcmc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pcmc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pcmc *ProductCategoryMajorCreate) SaveX(ctx context.Context) *ProductCategoryMajor {
	v, err := pcmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcmc *ProductCategoryMajorCreate) Exec(ctx context.Context) error {
	_, err := pcmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcmc *ProductCategoryMajorCreate) ExecX(ctx context.Context) {
	if err := pcmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pcmc *ProductCategoryMajorCreate) defaults() {
	if _, ok := pcmc.mutation.CreatedAt(); !ok {
		v := productcategorymajor.DefaultCreatedAt()
		pcmc.mutation.SetCreatedAt(v)
	}
	if _, ok := pcmc.mutation.UpdatedAt(); !ok {
		v := productcategorymajor.DefaultUpdatedAt()
		pcmc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pcmc *ProductCategoryMajorCreate) check() error {
	if _, ok := pcmc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProductCategoryMajor.created_at"`)}
	}
	if _, ok := pcmc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProductCategoryMajor.updated_at"`)}
	}
	if _, ok := pcmc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "ProductCategoryMajor.category"`)}
	}
	if v, ok := pcmc.mutation.Category(); ok {
		if err := productcategorymajor.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ProductCategoryMajor.category": %w`, err)}
		}
	}
	return nil
}

func (pcmc *ProductCategoryMajorCreate) sqlSave(ctx context.Context) (*ProductCategoryMajor, error) {
	_node, _spec := pcmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pcmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pcmc *ProductCategoryMajorCreate) createSpec() (*ProductCategoryMajor, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductCategoryMajor{config: pcmc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: productcategorymajor.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productcategorymajor.FieldID,
			},
		}
	)
	if value, ok := pcmc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productcategorymajor.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := pcmc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productcategorymajor.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := pcmc.mutation.Category(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: productcategorymajor.FieldCategory,
		})
		_node.Category = value
	}
	if nodes := pcmc.mutation.MinorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   productcategorymajor.MinorsTable,
			Columns: productcategorymajor.MinorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: productcategoryminor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pcmc.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   productcategorymajor.ProductsTable,
			Columns: productcategorymajor.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProductCategoryMajorCreateBulk is the builder for creating many ProductCategoryMajor entities in bulk.
type ProductCategoryMajorCreateBulk struct {
	config
	builders []*ProductCategoryMajorCreate
}

// Save creates the ProductCategoryMajor entities in the database.
func (pcmcb *ProductCategoryMajorCreateBulk) Save(ctx context.Context) ([]*ProductCategoryMajor, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcmcb.builders))
	nodes := make([]*ProductCategoryMajor, len(pcmcb.builders))
	mutators := make([]Mutator, len(pcmcb.builders))
	for i := range pcmcb.builders {
		func(i int, root context.Context) {
			builder := pcmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductCategoryMajorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcmcb *ProductCategoryMajorCreateBulk) SaveX(ctx context.Context) []*ProductCategoryMajor {
	v, err := pcmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcmcb *ProductCategoryMajorCreateBulk) Exec(ctx context.Context) error {
	_, err := pcmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcmcb *ProductCategoryMajorCreateBulk) ExecX(ctx context.Context) {
	if err := pcmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
