// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SeyramWood/ent/predicate"
	"github.com/SeyramWood/ent/purchaserequest"
)

// PurchaseRequestDelete is the builder for deleting a PurchaseRequest entity.
type PurchaseRequestDelete struct {
	config
	hooks    []Hook
	mutation *PurchaseRequestMutation
}

// Where appends a list predicates to the PurchaseRequestDelete builder.
func (prd *PurchaseRequestDelete) Where(ps ...predicate.PurchaseRequest) *PurchaseRequestDelete {
	prd.mutation.Where(ps...)
	return prd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (prd *PurchaseRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, prd.sqlExec, prd.mutation, prd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (prd *PurchaseRequestDelete) ExecX(ctx context.Context) int {
	n, err := prd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (prd *PurchaseRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(purchaserequest.Table, sqlgraph.NewFieldSpec(purchaserequest.FieldID, field.TypeInt))
	if ps := prd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, prd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	prd.mutation.done = true
	return affected, err
}

// PurchaseRequestDeleteOne is the builder for deleting a single PurchaseRequest entity.
type PurchaseRequestDeleteOne struct {
	prd *PurchaseRequestDelete
}

// Where appends a list predicates to the PurchaseRequestDelete builder.
func (prdo *PurchaseRequestDeleteOne) Where(ps ...predicate.PurchaseRequest) *PurchaseRequestDeleteOne {
	prdo.prd.mutation.Where(ps...)
	return prdo
}

// Exec executes the deletion query.
func (prdo *PurchaseRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := prdo.prd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{purchaserequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (prdo *PurchaseRequestDeleteOne) ExecX(ctx context.Context) {
	if err := prdo.Exec(ctx); err != nil {
		panic(err)
	}
}
