// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/SeyramWood/ent/merchant"
	"github.com/SeyramWood/ent/retailmerchant"
)

// RetailMerchant is the model entity for the RetailMerchant schema.
type RetailMerchant struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GhanaCard holds the value of the "ghana_card" field.
	GhanaCard string `json:"ghana_card,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName string `json:"last_name,omitempty"`
	// OtherName holds the value of the "other_name" field.
	OtherName string `json:"other_name,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// OtherPhone holds the value of the "other_phone" field.
	OtherPhone *string `json:"other_phone,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RetailMerchantQuery when eager-loading is set.
	Edges             RetailMerchantEdges `json:"edges"`
	merchant_retailer *int
}

// RetailMerchantEdges holds the relations/edges for other nodes in the graph.
type RetailMerchantEdges struct {
	// Merchant holds the value of the merchant edge.
	Merchant *Merchant `json:"merchant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MerchantOrErr returns the Merchant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RetailMerchantEdges) MerchantOrErr() (*Merchant, error) {
	if e.loadedTypes[0] {
		if e.Merchant == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: merchant.Label}
		}
		return e.Merchant, nil
	}
	return nil, &NotLoadedError{edge: "merchant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RetailMerchant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case retailmerchant.FieldID:
			values[i] = new(sql.NullInt64)
		case retailmerchant.FieldGhanaCard, retailmerchant.FieldLastName, retailmerchant.FieldOtherName, retailmerchant.FieldPhone, retailmerchant.FieldOtherPhone:
			values[i] = new(sql.NullString)
		case retailmerchant.FieldCreatedAt, retailmerchant.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case retailmerchant.ForeignKeys[0]: // merchant_retailer
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type RetailMerchant", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RetailMerchant fields.
func (rm *RetailMerchant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case retailmerchant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rm.ID = int(value.Int64)
		case retailmerchant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rm.CreatedAt = value.Time
			}
		case retailmerchant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				rm.UpdatedAt = value.Time
			}
		case retailmerchant.FieldGhanaCard:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ghana_card", values[i])
			} else if value.Valid {
				rm.GhanaCard = value.String
			}
		case retailmerchant.FieldLastName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[i])
			} else if value.Valid {
				rm.LastName = value.String
			}
		case retailmerchant.FieldOtherName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field other_name", values[i])
			} else if value.Valid {
				rm.OtherName = value.String
			}
		case retailmerchant.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				rm.Phone = value.String
			}
		case retailmerchant.FieldOtherPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field other_phone", values[i])
			} else if value.Valid {
				rm.OtherPhone = new(string)
				*rm.OtherPhone = value.String
			}
		case retailmerchant.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field merchant_retailer", value)
			} else if value.Valid {
				rm.merchant_retailer = new(int)
				*rm.merchant_retailer = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryMerchant queries the "merchant" edge of the RetailMerchant entity.
func (rm *RetailMerchant) QueryMerchant() *MerchantQuery {
	return (&RetailMerchantClient{config: rm.config}).QueryMerchant(rm)
}

// Update returns a builder for updating this RetailMerchant.
// Note that you need to call RetailMerchant.Unwrap() before calling this method if this RetailMerchant
// was returned from a transaction, and the transaction was committed or rolled back.
func (rm *RetailMerchant) Update() *RetailMerchantUpdateOne {
	return (&RetailMerchantClient{config: rm.config}).UpdateOne(rm)
}

// Unwrap unwraps the RetailMerchant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rm *RetailMerchant) Unwrap() *RetailMerchant {
	_tx, ok := rm.config.driver.(*txDriver)
	if !ok {
		panic("ent: RetailMerchant is not a transactional entity")
	}
	rm.config.driver = _tx.drv
	return rm
}

// String implements the fmt.Stringer.
func (rm *RetailMerchant) String() string {
	var builder strings.Builder
	builder.WriteString("RetailMerchant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rm.ID))
	builder.WriteString("created_at=")
	builder.WriteString(rm.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(rm.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ghana_card=")
	builder.WriteString(rm.GhanaCard)
	builder.WriteString(", ")
	builder.WriteString("last_name=")
	builder.WriteString(rm.LastName)
	builder.WriteString(", ")
	builder.WriteString("other_name=")
	builder.WriteString(rm.OtherName)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(rm.Phone)
	builder.WriteString(", ")
	if v := rm.OtherPhone; v != nil {
		builder.WriteString("other_phone=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// RetailMerchants is a parsable slice of RetailMerchant.
type RetailMerchants []*RetailMerchant

func (rm RetailMerchants) config(cfg config) {
	for _i := range rm {
		rm[_i].config = cfg
	}
}
