// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/SeyramWood/ent/suppliermerchant"
)

// SupplierMerchant is the model entity for the SupplierMerchant schema.
type SupplierMerchant struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Password holds the value of the "password" field.
	Password []byte `json:"-"`
	// GhanaCard holds the value of the "ghana_card" field.
	GhanaCard string `json:"ghana_card,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName string `json:"last_name,omitempty"`
	// OtherName holds the value of the "other_name" field.
	OtherName string `json:"other_name,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// OtherPhone holds the value of the "other_phone" field.
	OtherPhone *string `json:"other_phone,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// DigitalAddress holds the value of the "digital_address" field.
	DigitalAddress string `json:"digital_address,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupplierMerchant) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case suppliermerchant.FieldPassword:
			values[i] = new([]byte)
		case suppliermerchant.FieldID:
			values[i] = new(sql.NullInt64)
		case suppliermerchant.FieldUsername, suppliermerchant.FieldGhanaCard, suppliermerchant.FieldLastName, suppliermerchant.FieldOtherName, suppliermerchant.FieldPhone, suppliermerchant.FieldOtherPhone, suppliermerchant.FieldAddress, suppliermerchant.FieldDigitalAddress:
			values[i] = new(sql.NullString)
		case suppliermerchant.FieldCreatedAt, suppliermerchant.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type SupplierMerchant", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupplierMerchant fields.
func (sm *SupplierMerchant) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case suppliermerchant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sm.ID = int(value.Int64)
		case suppliermerchant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sm.CreatedAt = value.Time
			}
		case suppliermerchant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sm.UpdatedAt = value.Time
			}
		case suppliermerchant.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				sm.Username = value.String
			}
		case suppliermerchant.FieldPassword:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value != nil {
				sm.Password = *value
			}
		case suppliermerchant.FieldGhanaCard:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ghana_card", values[i])
			} else if value.Valid {
				sm.GhanaCard = value.String
			}
		case suppliermerchant.FieldLastName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[i])
			} else if value.Valid {
				sm.LastName = value.String
			}
		case suppliermerchant.FieldOtherName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field other_name", values[i])
			} else if value.Valid {
				sm.OtherName = value.String
			}
		case suppliermerchant.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				sm.Phone = value.String
			}
		case suppliermerchant.FieldOtherPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field other_phone", values[i])
			} else if value.Valid {
				sm.OtherPhone = new(string)
				*sm.OtherPhone = value.String
			}
		case suppliermerchant.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				sm.Address = value.String
			}
		case suppliermerchant.FieldDigitalAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field digital_address", values[i])
			} else if value.Valid {
				sm.DigitalAddress = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this SupplierMerchant.
// Note that you need to call SupplierMerchant.Unwrap() before calling this method if this SupplierMerchant
// was returned from a transaction, and the transaction was committed or rolled back.
func (sm *SupplierMerchant) Update() *SupplierMerchantUpdateOne {
	return (&SupplierMerchantClient{config: sm.config}).UpdateOne(sm)
}

// Unwrap unwraps the SupplierMerchant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sm *SupplierMerchant) Unwrap() *SupplierMerchant {
	tx, ok := sm.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupplierMerchant is not a transactional entity")
	}
	sm.config.driver = tx.drv
	return sm
}

// String implements the fmt.Stringer.
func (sm *SupplierMerchant) String() string {
	var builder strings.Builder
	builder.WriteString("SupplierMerchant(")
	builder.WriteString(fmt.Sprintf("id=%v", sm.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(sm.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(sm.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", username=")
	builder.WriteString(sm.Username)
	builder.WriteString(", password=<sensitive>")
	builder.WriteString(", ghana_card=")
	builder.WriteString(sm.GhanaCard)
	builder.WriteString(", last_name=")
	builder.WriteString(sm.LastName)
	builder.WriteString(", other_name=")
	builder.WriteString(sm.OtherName)
	builder.WriteString(", phone=")
	builder.WriteString(sm.Phone)
	if v := sm.OtherPhone; v != nil {
		builder.WriteString(", other_phone=")
		builder.WriteString(*v)
	}
	builder.WriteString(", address=")
	builder.WriteString(sm.Address)
	builder.WriteString(", digital_address=")
	builder.WriteString(sm.DigitalAddress)
	builder.WriteByte(')')
	return builder.String()
}

// SupplierMerchants is a parsable slice of SupplierMerchant.
type SupplierMerchants []*SupplierMerchant

func (sm SupplierMerchants) config(cfg config) {
	for _i := range sm {
		sm[_i].config = cfg
	}
}
