name: Build and Publish Docker Image
on:
  push:
    branches:
      - dev
jobs:
  build-and-publish:
    if: ${{github.ref == 'refs/heads/dev'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to DEV server on branch $GITHUB_REF"
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build . -t asinyoapi:dev
      - name: Publish to Dockerhub Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: seyramwood/asinyoapi
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}